# Generated by Django 3.0.6 on 2020-06-16 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='nombre_A',
            new_name='nombre',
        ),
    ]
