# Generated by Django 3.0.6 on 2020-09-28 02:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedido', '0003_auto_20200927_0214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Articulos',
        ),
    ]
